#MuseCoreModules:Synthesis&CompositionToolsinCommonLISP
Thisfilecontainsthemodulesforthesynthesizeandcomposewithinthe**Museproject.Thprimarycomponentsincludeoscillators,EGs,filters,effectsprocessors,andbasicutilities.
ToflexibilitywhilemaintainingmodularitythroughoutMuse'sarchitecturethesebuildingblocksaredesignedtoeasyintegratewitheachotherandedextendeduponbyusersforcustomimplementations. 
Thefundamentalutilitysandexamplesareincludedherebeforeclosingoffoverviewonpotentialfutureenhancements.